# Generated by Django 4.0.3 on 2022-04-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_title', models.CharField(default='Untitled Set', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date set created')),
                ('active', models.BooleanField(default=True, verbose_name='is the set active?')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='', max_length=200)),
                ('answer_text', models.CharField(default='', max_length=300)),
                ('created_date', models.DateTimeField(verbose_name='date card created')),
                ('rel_cardset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aceproc.cardset')),
            ],
        ),
    ]
