# Generated by Django 4.0.3 on 2022-04-06 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aceproc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date card created'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date set created'),
        ),
    ]
